config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'movies#index'
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	searchkick
	belongs_to :user
	has_many :reviews

	has_attached_file :image, styles: { medium: "300x400#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	validates :title, presence: true
	validates :description, length: { minimum: 10, maximum: 160 }
	validates :movie_length, presence: true
	validates :director, presence: true
	validates :rating, presence: true
	validates_attachment_presence :image
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie

	validates :rating, presence: true
	validates :comment, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :set_movie, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index,:show,:search]

	def search
		if params[:search].present?
			@movies = Movie.search(params[:search])
		else
			@movies = Movie.all
		end
	end

	def index
		@movies = Movie.all.order("created_at DESC")
	end

	def new
		@movie = current_user.movies.build
	end

	def create
		@movie = current_user.movies.build(movie_param)
		if @movie.save
			redirect_to @movie
		else
			render 'new'
		end
	end

	def show
		@movie = Movie.find(params[:id])
		@reviews = Review.where(movie_id: @movie.id).order('created_at DESC')

		if @reviews.blank?
			@avg_rating = 0
		else
			@avg_rating = @reviews.average(:rating).round(2)
		end
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		@movie = Movie.find(params[:id])
		if @movie.update_attributes(movie_param)
			redirect_to @movie
		else
			render 'edit'
		end
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.image = nil
		@movie.destroy
		redirect_to movies_path
	end


	private

	def set_movie
		@movie = Movie.find(params[:id])
	end

	def movie_param
		params.require(:movie).permit(:title,:description,:movie_length,:director,:rating,:image)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_review, only: [:destroy,:edit]
	before_action :set_movie
	before_action :authenticate_user!
	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_param)
		@review.user_id = current_user.id
		@review.movie_id = @movie.id

		if @review.save
			redirect_to @movie
		else
			render 'new'
		end
	end

	private

	def set_review
		@review = Review.find(params[:id])
	end

	def set_movie
		@movie = Movie.find(params[:movie_id])
	end

	def review_param
		params.require(:review).permit(:rating, :comment)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role= "navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Movie Review", movies_path, class: 'navbar-brand' %> 
		</div>
		<div class="collapse navbar-collapse" id="menu">
			<ul class="nav navbar-nav">
				<% if user_signed_in? %>
					<li><%= link_to 'New Movie', new_movie_path, class: 'active' %></li>
					<li><%= link_to 'Account', edit_user_registration_path %></li>
					<li><%= link_to 'Sign Out',  destroy_user_session_path, method: :delete %></li>
					
				<% else %>
					<li><%= link_to 'Sign Up', new_user_registration_path, class: 'active' %></li>
					<li><%= link_to 'Sign In', new_user_session_path, class: 'active' %></li>
				<% end %>
			</ul>
			<%= form_tag search_movies_path, method: :get, class: 'navbar-form navbar-right', role: 'search' do %>
				<%= text_field_tag :search, params[:search], class: 'form-control' %>
				<%= submit_tag 'Search', name: nil, class: 'btn btn-default' %>
			<% end %>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoviesReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name,msg| %>
			<%= content_tag(:div, msg, class: 'alert alert-info' ) %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
	<% if @movie.errors.any? %>
		<div id='error'>
			<h3><%= pluralize(@movie.errors.count,'error') %> prevented this post from edit</h3>
			<ul>
				<% @movie.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p><%= f.label :title %><br>
		<%= f.text_field :title %></p>

	<p><%= f.label :description %><br>
		<%= f.text_field :description %></p>

	<p><%= f.label :movie_length, 'Movie Length' %><br>
		<%= f.text_field :movie_length %></p>

	<p><%= f.label :director, 'Director Name' %><br>
		<%= f.text_field :director %></p>

	<p><%= f.label :rating %><br>
		<%= f.number_field :rating %></p>

	<p><%= f.label :image %><br>
		<%= f.file_field :image %></p>

	<p><%= f.submit %></p>
<% end %>

app/views/movies/edit.html.erb
<%= render 'form' %>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
	<div class="jumbotron">
		<h2>Your Favorite Movies Reviewed Here!</h2>
		<p><%= link_to 'Sign Up Here To Wite Review', new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
	</div>
<% end %>
<div class="row">
	<% @movies.each do |movie| %>
		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
			</div>
		</div>
	<% end %>
</div>

app/views/movies/new.html.erb
<%= render 'form' %>

app/views/movies/search.html.erb
<div class="row">
	<% @movies.each do |movie| %>
		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
			</div>
		</div>
	<% end %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
				<%= image_tag @movie.image.url(:medium), class: 'image' %>
				
				<div class="table-responsive">
					<table class="table">
						<tr>
							<td>
								<div class="star-rating" data-score=<%= @avg_rating %> ></div>
								<em><%= "#{@reviews.length}" %> reviews</em>
							</td>
						</tr>
						<tr>
							<td><strong>Title:</strong></td>
							<td><%= @movie.title %></td>
						</tr>
						<tr>
							<td><strong>Description:</strong></td>
							<td><%= @movie.description %></td>
						</tr>
						<tr>
							<td><strong>Movie Length:</strong></td>
							<td><%= @movie.movie_length %></td>
						</tr>
						<tr>
							<td><strong>Directed By:</strong></td>
							<td><%= @movie.director %></td>
						</tr>
						<tr>
							<td><%= link_to 'Write Review', new_movie_review_path(@movie) %></td>
						</tr>
						<tr>
							<td>
								<%= link_to "Edit", edit_movie_path %> | <%= link_to "Back", movies_path %>
							</td>
						</tr>
					</table>
				</div>
			</div>
			<div class="col-md-7 col-offset-1">
				<h3 class="review-title"><strong>Title:</strong> <%= @movie.title %></h3>
				<p><strong>Description:</strong> <%= @movie.description %></p>

				<% if @reviews.blank? %>
					<p>This movie not reviewd yet!!</p>
					<%= link_to 'Write Review', new_movie_review_path(@movie), class: 'btn btn-danger btn-lg' %>
				<% else %>
					<% @reviews.each do |review| %>
						<div class="reviews">
							<div class="star-rating" data-score=<%= review.rating %>></div>
							<p><%= review.comment %></p>
						</div>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<script>
	$('.star-rating').raty({
		path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
	<% if @review.errors.any? %>
		<div id="error">
			<h2><%= pluralize(@review.errors.count, "error") %> have stop to save review</h2>
			<ul>
				<% @review.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div id="star-rating"></div>
	<p><%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</p>
	<p><%= f.submit %></p>
<% end %>
<script>
	$('#star-rating').raty({
		path: '/assets/',
		scoreName: 'review[rating]' 
	});
</script>

<!-- review[rating]-> review is model and rating is column name -->
	

app/views/reviews/edit.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<h2>Edit Review</h2>
		<%= render 'form' %>
		<%= link_to 'Back', movie_path(@movies) %>
	</div>
</div>

app/views/reviews/new.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<h2>New Review</h2>
		<%= render 'form' %>
		<%= link_to 'Back', movie_path(@movie) %>
	</div>
</div>